added pong command
robertvargas-irq/modern-web-final-project pull request #5
Opened 2023-04-21 21:02 UTC by matrom01-v2

2023-04-21 21:58 UTC, robertvargas-irq requested changes
Changes pending; Prettier needs to be ran.

2023-04-21 21:58 UTC, robertvargas-irq commented on src/commands/pong.ts
Run Prettier on your file.
Install the Prettier extension on Visual Studio Code and run it on a file with Shift+Alt+F.

2023-04-22 04:01 UTC, matrom01-v2 commented on src/commands/pong.ts
fixed with prettier

2023-04-22 04:08 UTC, robertvargas-irq approved these changes
Looks great!

2023-04-22 04:08 UTC, merged